#Test id=0
- device: blackhole
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [10, 8], ublock: [6, 1], df: Bfp8_b, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3ca13a80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [8, 1], ublock: [1, 1], df: Float32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3d6c8940]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [1, 1], t: 1, mblock: [5, 1], ublock: [3, 1], df: Float16_b, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3da9f780]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [10, 1], ublock: [6, 1], df: Float16_b, tile_dim: [32, 32], input: drainer, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3ef1ff80]], }'
  queue_settings_out0: ''
  op0: 'op: {type: depthwise, grid_size: [1, 1], t: 1, mblock: [10, 1], ublock: [6, 1], out_df: Float16_b, grid_loc: [0, 0], inputs: [input_0, input_1, input_2], in_df: [Bfp8_b, Float32, Float16_b], math_fidelity: HiFi3, intermed_df: Float16_b, acc_df: Float16, attributes: {bias: true, m_k: 8, u_kt: 1, l1_acc: true, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], input_1_tms: [], input_2_tms: [broadcast: {r: 4}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [10, 1], ublock: [6, 1], out_df: Float16_b, grid_loc: [0, 1], inputs: [op], in_df: [Float16_b], math_fidelity: HiFi3, intermed_df: Bfp8_b, acc_df: Float16_b, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 6, mblock: [3, 8], ublock: [2, 1], df: Bfp8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x10efd0c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 6, mblock: [1, 1], ublock: [1, 1], df: Bfp8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x29db9080]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 6, mblock: [6, 1], ublock: [6, 1], df: Float16, tile_dim: [32, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2e050580]], }'
  queue_settings_out0: ''
  op0: 'op: {type: depthwise, grid_size: [1, 1], t: 6, mblock: [6, 1], ublock: [6, 1], out_df: Float16, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Bfp8, Bfp8], math_fidelity: HiFi4, intermed_df: Float16, acc_df: Float16, attributes: {stoch_rnd_mode: fpu, m_k: 8, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 6}, ], input_1_tms: [broadcast: {r: 8}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 6, mblock: [6, 1], ublock: [6, 1], out_df: Float16, grid_loc: [0, 1], inputs: [op], in_df: [Float16], math_fidelity: HiFi4, intermed_df: Float16, acc_df: Float16_b, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [3, 1], ublock: [1, 1], df: Bfp8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x21922180]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 1], ublock: [1, 1], df: Bfp8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2ee98fc0]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [6, 1], df: Bfp8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x38451340]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [6, 1], df: Float16, tile_dim: [32, 32], input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3c094380]], }'
  queue_settings_out0: ''
  op0: 'op: {type: depthwise, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [6, 1], out_df: Float16, grid_loc: [0, 0], inputs: [input_0, input_1, input_2], in_df: [Bfp8, Bfp8, Bfp8], math_fidelity: HiFi4, intermed_df: Float16, acc_df: Float16_b, attributes: {bias: true, m_k: 3, u_kt: 1, kernel_broadcast_per_t : {input_0 : 12}, kernel_broadcast : {input_1 : 1}, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, broadcast: {c: 3}, ], input_1_tms: [broadcast: {r: 3}, ], input_2_tms: [], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [6, 1], out_df: Float16, grid_loc: [0, 1], inputs: [op], in_df: [Float16], math_fidelity: HiFi4, intermed_df: Bfp8, acc_df: Float16_b, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [4, 4], ublock: [1, 1], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2869e240]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 8, mblock: [4, 1], ublock: [1, 1], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2a4d0100]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 8, mblock: [6, 1], ublock: [6, 1], df: Float16_b, input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3c7cd980]], }'
  queue_settings_out0: ''
  op0: 'op: {type: depthwise, grid_size: [1, 1], t: 8, mblock: [6, 1], ublock: [6, 1], out_df: Float16_b, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Float32, Float32], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16_b, attributes: {stoch_rnd_mode: none, m_k: 4, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 9}, broadcast: {z: 8}, ], input_1_tms: [], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 8, mblock: [6, 1], ublock: [6, 1], out_df: Float16_b, grid_loc: [0, 1], inputs: [op], in_df: [Float16_b], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16, attributes: {stoch_rnd_mode: none, vector: rc, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [8, 1], ublock: [1, 1], df: Float32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2a0ed5c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [2, 1], ublock: [1, 1], df: Bfp8_b, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3644a540]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 4, mblock: [8, 1], ublock: [4, 1], df: Float16_b, tile_dim: [32, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3f6ad5c0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: depthwise, grid_size: [1, 1], t: 4, mblock: [8, 1], ublock: [4, 1], out_df: Float16_b, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Float32, Bfp8_b], math_fidelity: HiFi3, intermed_df: Float32, acc_df: Float16, attributes: {relu_en: true, relu_mode: min, relu_threshold: 0.360000, stoch_rnd_mode: none, m_k: 8, u_kt: 1, kernel_broadcast : {input_0 : 16}, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, broadcast: {c: 8}, broadcast: {z: 4}, ], input_1_tms: [broadcast: {r: 4}, broadcast: {z: 4}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 4, mblock: [8, 1], ublock: [4, 1], out_df: Float16_b, grid_loc: [0, 1], inputs: [op], in_df: [Float16_b], math_fidelity: HiFi3, intermed_df: Bfp8_b, acc_df: Float16_b, attributes: {stoch_rnd_mode: none, vector: rc, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=5
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [9, 12], ublock: [8, 1], df: Bfp8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x242b75c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [2, 1], ublock: [1, 1], df: Bfp8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x32b88880]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [1, 1], t: 1, mblock: [2, 1], ublock: [4, 1], df: Float16, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3b8db980]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [9, 1], ublock: [8, 1], df: Float16, tile_dim: [32, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3e100ac0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: depthwise, grid_size: [1, 1], t: 1, mblock: [9, 1], ublock: [8, 1], out_df: Float16, grid_loc: [0, 0], inputs: [input_0, input_1, input_2], in_df: [Bfp8, Bfp8, Float16], math_fidelity: HiFi3, intermed_df: Float16, acc_df: Float16_b, attributes: {bias: true, m_k: 12, u_kt: 1, kernel_broadcast : {input_2 : 8}, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], input_1_tms: [broadcast: {r: 6}, ], input_2_tms: [broadcast: {r: 9}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [9, 1], ublock: [8, 1], out_df: Float16, grid_loc: [0, 1], inputs: [op], in_df: [Float16], math_fidelity: HiFi3, intermed_df: Float16, acc_df: Float16_b, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
