name: "Install dependencies"
description: "Installs dependencies on GitHub Actions runners"

inputs:
  os:
    description: 'Runner OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify ubuntu only
      shell: bash
      run: |
        if ! echo ${{ inputs.os }} | grep -q "ubuntu"; then
          echo "${{ inputs.os }} does not seem to be ubuntu"
        fi
    - name: Assert requested os exists in dependencies
      shell: bash
      run: |
        if ! jq -e ".\"${{ inputs.os }}\" != null" $GITHUB_ACTION_PATH/dependencies.json; then
          echo "${{ inputs.os }} does not exist as a supported os in $GITHUB_ACTION_PATH/dependencies.json"
        fi
    - name: Retrieve and install pkg deps based on OS
      id: retrieve-pkg-deps
      shell: bash
      run: |
        DEPENDENCIES=$(jq -r --arg os "${{ inputs.os }}" '.[$os] | .[]' $GITHUB_ACTION_PATH/dependencies.json)
        echo $DEPENDENCIES
        sudo apt update
        sudo apt install $DEPENDENCIES
