#Test id=0
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 6], ublock: [8, 6], df: Float32, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x33d2d440]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 9], ublock: [1, 4], df: Float32, tile_dim: [16, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x384e5540]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 9], ublock: [1, 4], out_df: Float32, tile_dim: [16, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Float32], math_fidelity: HiFi2, intermed_df: Float32, acc_df: Float16_b, attributes: {type: max, dim: r, m_k: 8, u_kt: 8, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [1, 9], ublock: [1, 4], out_df: Float32, tile_dim: [16, 32], grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi2, intermed_df: Float32, acc_df: Float32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 16], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [6, 8], ublock: [1, 16], df: Bfp8, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x172b1a80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 16], ublock: [1, 8], df: Bfp8, input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2c396500]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 16], ublock: [1, 8], out_df: Bfp8, tile_dim: [32, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8], math_fidelity: LoFi, intermed_df: Bfp8, acc_df: Float16_b, attributes: {type: max, dim: r, m_k: 10, u_kt: 3, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 5}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [1, 16], ublock: [1, 8], out_df: Bfp8, tile_dim: [32, 32], grid_loc: [0, 1], inputs: [op], in_df: [Bfp8], math_fidelity: LoFi, intermed_df: Bfp8, acc_df: Float16, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 60, mblock: [2, 2], ublock: [2, 4], df: Float32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x37700c80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 30, mblock: [2, 2], ublock: [2, 4], df: Float32, tile_dim: [32, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3b4c9a00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 30, mblock: [2, 2], ublock: [2, 4], out_df: Float32, grid_loc: [0, 0], inputs: [input_0], in_df: [Float32], math_fidelity: HiFi3, intermed_df: Float32, acc_df: Float16, attributes: {type: max, dim: z, accumulate: true, z: 2, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 30, mblock: [2, 2], ublock: [2, 4], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi3, intermed_df: Float16_b, acc_df: Float16_b, attributes: {stoch_rnd_mode: none, vector: rc, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [2, 7], ublock: [1, 9], df: Float16_b, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x18128840]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [4, 1], df: Float16_b, tile_dim: [32, 16], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x21a68d40]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [4, 1], out_df: Float16_b, tile_dim: [32, 16], grid_loc: [0, 0], inputs: [input_0], in_df: [Float16_b], math_fidelity: HiFi3, intermed_df: Float16_b, acc_df: Float32, attributes: {type: max, dim: c, m_k: 9, u_kt: 7, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [4, 1], out_df: Float16_b, tile_dim: [32, 16], grid_loc: [0, 1], inputs: [op], in_df: [Float16_b], math_fidelity: HiFi3, intermed_df: Float16_b, acc_df: Float16_b, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 3], ublock: [11, 4], df: Bfp8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1816b5c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 12], ublock: [1, 8], df: Bfp8, tile_dim: [32, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1af1aec0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 12], ublock: [1, 8], out_df: Bfp8, grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8], math_fidelity: HiFi2, intermed_df: Bfp8, acc_df: Float16_b, attributes: {type: max, dim: r, m_k: 11, u_kt: 6, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 6}, broadcast: {c: 8}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [1, 12], ublock: [1, 8], out_df: Bfp8, grid_loc: [0, 1], inputs: [op], in_df: [Bfp8], math_fidelity: HiFi2, intermed_df: Bfp8, acc_df: Float16, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=5
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [8, 5], ublock: [2, 7], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x1b95f300]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 7], df: Float32, input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3a175080]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 7], out_df: Float32, grid_loc: [0, 0], inputs: [input_0], in_df: [Float32], math_fidelity: LoFi, intermed_df: Float32, acc_df: Float16, attributes: {type: max, dim: r, stoch_rnd_mode: none, m_k: 4, u_kt: 16, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 7], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: LoFi, intermed_df: Bfp8_b, acc_df: Float16, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
