#Test id=0
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [8, 2], ublock: [4, 8], df: Float16_b, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x37d12000]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 2], ublock: [1, 8], df: Float16_b, input: op, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3a4f4f80]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 2], ublock: [1, 8], out_df: Float16_b, grid_loc: [0, 0], inputs: [input_0], in_df: [Float16_b], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16, attributes: {type: max, dim: r, stoch_rnd_mode: none, m_k: 8, u_kt: 4, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 18, mblock: [1, 8], ublock: [2, 6], df: Float32, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x13299100], [0, 0x14e05140]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 18, mblock: [1, 8], ublock: [1, 6], df: Float32, tile_dim: [2, 32], input: op, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1f424400], [0, 0x201da440]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 18, mblock: [1, 8], ublock: [1, 6], out_df: Float32, tile_dim: [2, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Float32], math_fidelity: LoFi, intermed_df: Float32, acc_df: Float16, attributes: {type: max, dim: r, stoch_rnd_mode: fpu, m_k: 2, u_kt: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 5}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 2], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: blackhole
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 6, mblock: [4, 2], ublock: [1, 3], df: Bfp8_b, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x1f5e3300], [0, 0x1f60bb40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 2, mblock: [14, 3], ublock: [2, 2], df: Bfp8_b, input: op, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x1f7163c0], [0, 0x1f774c00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 2, mblock: [14, 3], ublock: [2, 2], out_df: Bfp8_b, grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8_b], math_fidelity: HiFi4, intermed_df: Bfp8_b, acc_df: Float16_b, attributes: {type: max, dim: z, accumulate: true, z: 3, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 7}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 1, mblock: [14, 6], ublock: [4, 4], df: Float16, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x185de640], [0, 0x18b48680]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 2, mblock: [1, 8], ublock: [1, 3], df: Float16, tile_dim: [8, 32], input: op, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x368f1d00], [0, 0x36923540]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 2, mblock: [1, 8], ublock: [1, 3], out_df: Float16, tile_dim: [8, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Float16], math_fidelity: HiFi4, intermed_df: Float16, acc_df: Float16_b, attributes: {type: max, dim: r, m_k: 7, u_kt: 8, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {z: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 8], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 1, mblock: [5, 5], ublock: [15, 5], df: Float16_b, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x25cd8900], [0, 0x26bf3c40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 6, mblock: [1, 5], ublock: [1, 5], df: Float16_b, input: op, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3f9b8f00], [0, 0x3faee540]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 6, mblock: [1, 5], ublock: [1, 5], out_df: Float16_b, tile_dim: [32, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Float16_b], math_fidelity: HiFi3, intermed_df: Float16_b, acc_df: Float16, attributes: {type: max, dim: r, relu_en: true, relu_mode: min, relu_threshold: 0.750000, stoch_rnd_mode: fpu, m_k: 15, u_kt: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {z: 6}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=5
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [6, 5], ublock: [7, 8], df: Bfp8_b, tile_dim: [32, 32], input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1225b980]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 8], df: Bfp8_b, tile_dim: [8, 32], input: op, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x14fa4a00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 8], out_df: Bfp8_b, tile_dim: [8, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8_b], math_fidelity: HiFi2, intermed_df: Bfp8_b, acc_df: Float16_b, attributes: {type: max, dim: r, relu_en: true, relu_mode: min, relu_threshold: 0.470000, m_k: 6, u_kt: 7, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 8], check_tile_cols_range: [1, 32] }'
#Test id=6
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 10, mblock: [3, 6], ublock: [1, 8], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x34165d40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 10, mblock: [1, 8], ublock: [1, 6], df: Float32, input: op, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3d60b300]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 10, mblock: [1, 8], ublock: [1, 6], out_df: Float32, grid_loc: [0, 0], inputs: [input_0], in_df: [Float32], math_fidelity: HiFi2, intermed_df: Float32, acc_df: Float16, attributes: {type: max, dim: r, stoch_rnd_mode: none, m_k: 3, u_kt: 2, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=7
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 10, mblock: [1, 14], ublock: [2, 4], df: Float16, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x28013440], [0, 0x2921f480]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 1, mblock: [1, 14], ublock: [2, 4], df: Float16, input: op, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2d72a800], [0, 0x2d8f8840]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 1, mblock: [1, 14], ublock: [2, 4], out_df: Float16, grid_loc: [0, 0], inputs: [input_0], in_df: [Float16], math_fidelity: HiFi4, intermed_df: Float16, acc_df: Float16_b, attributes: {type: max, dim: z, accumulate: true, z: 10, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=8
- device: blackhole
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 30, mblock: [7, 1], ublock: [1, 9], df: Bfp8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x21e4e0c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 6, mblock: [14, 3], ublock: [1, 3], df: Bfp8, input: op, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3b158e00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 6, mblock: [14, 3], ublock: [1, 3], out_df: Bfp8, grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8], math_fidelity: HiFi3, intermed_df: Bfp8, acc_df: Float16, attributes: {type: max, dim: z, accumulate: true, z: 5, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=9
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 18, mblock: [5, 2], ublock: [1, 2], df: Bfp8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x22dbe100], [0, 0x230e8140]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 6, mblock: [5, 2], ublock: [1, 2], df: Bfp8, input: op, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2c8803c0], [0, 0x2c98e400]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 6, mblock: [5, 2], ublock: [1, 2], out_df: Bfp8, grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8], math_fidelity: HiFi2, intermed_df: Bfp8, acc_df: Float16_b, attributes: {type: max, dim: z, relu_en: true, relu_mode: min, relu_threshold: 0.030000, accumulate: true, z: 3, stoch_rnd_mode: none, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=10
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [2, 13], ublock: [4, 4], df: Bfp8, tile_dim: [32, 32], input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3107a500]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 13], ublock: [1, 4], df: Bfp8, input: op, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x38519dc0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 13], ublock: [1, 4], out_df: Bfp8, tile_dim: [32, 32], grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8], math_fidelity: HiFi3, intermed_df: Bfp8, acc_df: Float16, attributes: {type: max, dim: r, stoch_rnd_mode: none, m_k: 16, u_kt: 2, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=11
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 14, mblock: [5, 1], ublock: [1, 5], df: Bfp8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1b66f480], [0, 0x1b7342c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 1, mblock: [8, 5], ublock: [5, 1], df: Bfp8, input: op, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1da4b300], [0, 0x1dabbb40]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 1, mblock: [8, 5], ublock: [5, 1], out_df: Bfp8, grid_loc: [0, 0], inputs: [input_0], in_df: [Bfp8], math_fidelity: LoFi, intermed_df: Bfp8, acc_df: Float16_b, attributes: {type: max, dim: z, accumulate: true, z: 14, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
