#Test id=0
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 13], ublock: [1, 1], df: Int32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x31bcd600]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 13], ublock: [2, 1], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x38f17700]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [4, 13], ublock: [1, 1], df: Float32, input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3a722140]], }'
  queue_settings_out0: ''
  op0: 'op: {type: dequantization, grid_size: [1, 1], t: 1, mblock: [4, 13], ublock: [1, 1], out_df: Float32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int32, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {stoch_rnd_mode: fpu, zero_point: 27, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, ], input_1_tms: [broadcast: {r: 2}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [4, 13], ublock: [1, 1], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: blackhole
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 1], ublock: [3, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x18bc9f00]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 1], ublock: [3, 1], df: Float32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3a4e8e40]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [6, 1], ublock: [3, 1], df: Float32, tile_dim: [32, 32], input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3a5b0f80]], }'
  queue_settings_out0: ''
  op0: 'op: {type: dequantization, grid_size: [1, 1], t: 1, mblock: [6, 1], ublock: [3, 1], out_df: Float32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {kernel_broadcast : {input_1 : 3}, zero_point: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 6}, ], input_1_tms: [broadcast: {r: 6}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [6, 1], ublock: [3, 1], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16, attributes: {stoch_rnd_mode: none, vector: rc, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 4, mblock: [3, 3], ublock: [1, 3], df: Int8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x21d4ff80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 1], ublock: [1, 9], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2b851c80]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 4, mblock: [2, 9], ublock: [3, 1], df: Float32, input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2bf1c540]], }'
  queue_settings_out0: ''
  op0: 'op: {type: dequantization, grid_size: [1, 1], t: 4, mblock: [2, 9], ublock: [3, 1], out_df: Float32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {stoch_rnd_mode: none, zero_point: 54, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, ], input_1_tms: [broadcast: {r: 6}, broadcast: {z: 4}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 4, mblock: [2, 9], ublock: [3, 1], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi4, intermed_df: Bfp8_b, acc_df: Float32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 3], ublock: [1, 2], df: Int8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x12ef8e80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [3, 6], ublock: [3, 1], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3c1e37c0]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [3, 6], ublock: [3, 1], df: Float32, tile_dim: [32, 32], input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3e421f80]], }'
  queue_settings_out0: ''
  op0: 'op: {type: dequantization, grid_size: [1, 1], t: 1, mblock: [3, 6], ublock: [3, 1], out_df: Float32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 9}, ], input_1_tms: [], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [3, 6], ublock: [3, 1], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: blackhole
  loop_count: 2
  input_count: 2
  target_device: 0
  queue_wrap_size: 16
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [8, 2], ublock: [3, 1], df: Int32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x24ad1a40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [6, 1], ublock: [4, 1], df: Float32, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2eeb3b00]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [8, 2], ublock: [3, 1], df: Float32, tile_dim: [32, 32], input: drainer, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x3039cdc0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: dequantization, grid_size: [1, 1], t: 1, mblock: [8, 2], ublock: [3, 1], out_df: Float32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int32, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], input_1_tms: [broadcast: {c: 2}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [8, 2], ublock: [3, 1], out_df: Float32, grid_loc: [0, 1], inputs: [op], in_df: [Float32], math_fidelity: HiFi4, intermed_df: Float16_b, acc_df: Float16_b, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=5
- device: blackhole
  loop_count: 1
  input_count: 2
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 4], ublock: [6, 2], df: Int32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2949a040]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 4], ublock: [2, 2], df: Float32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3b5150c0]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [12, 4], ublock: [1, 2], df: Int8, input: drainer, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3d0e0200]], }'
  queue_settings_out0: ''
  op0: 'op: {type: requantization, grid_size: [1, 1], t: 1, mblock: [12, 4], ublock: [1, 2], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int32, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {stoch_rnd_mode: none, kernel_broadcast_per_t : {input_1 : 32}, zero_point: 69, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, ], input_1_tms: [broadcast: {r: 6}, ], }'
  op1: 'drainer: {type: datacopy, grid_size: [1, 1], t: 1, mblock: [12, 4], ublock: [1, 2], out_df: Int8, grid_loc: [0, 1], inputs: [op], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
